# This is a basic workflow to help you get started with Actions

name: deploy

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
permissions:
  contents: read
  pages: write
  id-token: write


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      # Setup Node to serve /dist folder with bundeled js sourced within index.html
      - name: Setup Node.js 
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Install Dependencies
        run: npm install
      - name: Build Application
        run: npm run build
      # upload the built dist folder as an artifact to be downloaded and used in actions below
      - name: Upload dist folder
        uses: actions/upload-artifact@v3
        with:
          name: app-build
          path: dist
          
    
      - name: Download build artifacts
        uses: actions/download-artifact@v3
        with:
          name: app-build

      # use the upload-pages-artifact action to upload the dist folder that was built and uploaded in the previous actions
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          # specify the dist director in order for the built files to be served and used as part of the final application deployment
          path: dist

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2
        with:
          token: ${{ secrets.GH_TOKEN }}